# Generated by Django 5.0.7 on 2024-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
